-- ./settings.reader.lua
return {
    ["auto_save_settings_interval_minutes"] = 15,
    ["auto_standby_timeout_seconds"] = -1,
    ["auto_suspend_timeout_seconds"] = 900,
    ["autodim_duration_seconds"] = 5,
    ["autodim_fraction"] = 20,
    ["autodim_starttime_minutes"] = -1,
    ["autoshutdown_timeout_seconds"] = 259200,
    ["autostart_profiles"] = {
        ["uwu"] = true,
    },
    ["autoturn_distance"] = 1,
    ["autoturn_timeout_seconds"] = 0,
    ["autowarmth_fl_off_during_day_offset_s"] = 0,
    ["autowarmth_timezone"] = 0,
    ["bookmarks_items_font_size"] = 19,
    ["bookmarks_items_per_page"] = 14,
    ["bookmarks_items_text_type"] = "note",
    ["closed_rotation_mode"] = 0,
    ["collate"] = "strcoll",
    ["color_rendering"] = true,
    ["coverbrowser_initial_default_setup_done"] = true,
    ["cre_font_family_fonts"] = {},
    ["cre_fonts_recently_selected"] = {
        [1] = "Droid Sans Mono",
        [2] = "FreeSans",
        [3] = "FreeSerif",
        [4] = "MyScriptInter",
        [5] = "Noto Naskh Arabic",
        [6] = "Noto Sans",
        [7] = "Noto Sans Arabic UI",
        [8] = "Noto Sans Bengali UI",
        [9] = "Noto Sans CJK SC",
        [10] = "Noto Sans Devanagari UI",
        [11] = "Noto Serif",
        [12] = "STIX Two Math",
        [13] = "STIX Two Text",
    },
    ["cre_header_author"] = 1,
    ["cre_header_auto_refresh"] = 1,
    ["cre_header_battery"] = 1,
    ["cre_header_battery_percent"] = 0,
    ["cre_header_chapter_marks"] = 1,
    ["cre_header_clock"] = 1,
    ["cre_header_page_count"] = 1,
    ["cre_header_page_number"] = 1,
    ["cre_header_reading_percent"] = 0,
    ["cre_header_title"] = 1,
    ["default_highlight_action"] = "dictionary",
    ["dev_no_c_blitter"] = false,
    ["device_id"] = "0813649A299B4E4BB028484273FED686",
    ["device_status_battery_alarm"] = true,
    ["device_status_battery_interval_minutes"] = 10,
    ["device_status_battery_threshold"] = 20,
    ["device_status_battery_threshold_high"] = 100,
    ["device_status_memory_interval_minutes"] = 5,
    ["device_status_memory_threshold"] = 100,
    ["dicts_disabled"] = {},
    ["dicts_order"] = {},
    ["dimension_units"] = "mm",
    ["document_metadata_folder"] = "doc",
    ["duration_format"] = "classic",
    ["exporter"] = {
        ["flomo"] = {
            ["enabled"] = false,
        },
        ["html"] = {
            ["enabled"] = false,
        },
        ["joplin"] = {
            ["enabled"] = false,
        },
        ["json"] = {
            ["enabled"] = false,
        },
        ["markdown"] = {
            ["formatting_options"] = {
                ["invert"] = "bold",
                ["lighten"] = "italic",
                ["strikeout"] = "strikethrough",
                ["underscore"] = "underline_markdownit",
            },
            ["highlight_formatting"] = true,
        },
        ["memos"] = {
            ["enabled"] = false,
        },
        ["my_clippings"] = {
            ["enabled"] = false,
        },
        ["readwise"] = {
            ["enabled"] = false,
        },
        ["text"] = {
            ["enabled"] = false,
        },
        ["xmnote"] = {
            ["enabled"] = false,
        },
    },
    ["filemanagermenu_tab_index"] = 5,
    ["folder_shortcuts"] = {},
    ["footer"] = {
        ["align"] = "right",
        ["all_at_once"] = true,
        ["auto_refresh_time"] = true,
        ["battery"] = true,
        ["battery_hide_threshold"] = 50,
        ["book_author"] = false,
        ["book_author_max_width_pct"] = 30,
        ["book_chapter"] = true,
        ["book_chapter_max_width_pct"] = 30,
        ["book_time_to_read"] = true,
        ["book_title"] = true,
        ["book_title_max_width_pct"] = 55,
        ["bookmark_count"] = false,
        ["bottom_horizontal_separator"] = false,
        ["chapter_progress"] = false,
        ["chapter_progress_bar"] = false,
        ["chapter_time_to_read"] = false,
        ["container_bottom_padding"] = 3,
        ["container_height"] = 14,
        ["disable_progress_bar"] = true,
        ["disabled"] = false,
        ["frontlight"] = false,
        ["hide_empty_generators"] = false,
        ["initial_marker"] = false,
        ["item_prefix"] = "icons",
        ["items_separator"] = "bar",
        ["lock_tap"] = false,
        ["mem_usage"] = false,
        ["order"] = {
            [0] = "off",
            [1] = "book_title",
            [2] = "book_chapter",
            [3] = "book_author",
            [4] = "page_progress",
            [5] = "pages_left_book",
            [6] = "pages_left",
            [7] = "percentage",
            [8] = "book_time_to_read",
            [9] = "chapter_time_to_read",
            [10] = "frontlight",
            [11] = "mem_usage",
            [12] = "bookmark_count",
            [13] = "chapter_progress",
            [14] = "frontlight_warmth",
            [15] = "custom_text",
            [16] = "page_turning_inverted",
            [17] = "time",
            [18] = "battery",
            [19] = "wifi_status",
        },
        ["page_progress"] = true,
        ["page_turning_inverted"] = false,
        ["pages_left"] = false,
        ["pages_left_book"] = false,
        ["pages_left_includes_current_page"] = true,
        ["percentage"] = false,
        ["progress_bar_min_width_pct"] = 20,
        ["progress_bar_position"] = "alongside",
        ["progress_margin"] = false,
        ["progress_margin_width"] = 10,
        ["progress_pct_format"] = "0",
        ["progress_style_thick_height"] = 7,
        ["progress_style_thin"] = false,
        ["progress_style_thin_height"] = 3,
        ["reclaim_height"] = false,
        ["skim_widget_on_hold"] = false,
        ["text_font_bold"] = false,
        ["text_font_size"] = 12,
        ["time"] = true,
        ["toc_markers"] = true,
        ["toc_markers_width"] = 2,
        ["wifi_status"] = true,
    },
    ["frontlight_intensity"] = 7,
    ["frontlight_warmth"] = 30,
    ["ges_tap_interval_on_keyboard_ms"] = 0,
    ["highlight_lighten_factor"] = 0.2,
    ["highlight_long_hold_threshold_s"] = 3,
    ["history_filter"] = "all",
    ["httpinspector_port"] = "8080",
    ["inertial_scroll"] = false,
    ["input_lock_gsensor"] = true,
    ["is_frontlight_on"] = true,
    ["keyboard_key_font_size"] = 22,
    ["keyboard_layouts"] = {},
    ["kosync"] = {
        ["auto_sync"] = false,
        ["checksum_method"] = 0,
        ["sync_backward"] = 3,
        ["sync_forward"] = 1,
    },
    ["language"] = "C",
    ["last_migration_date"] = 20240915,
    ["lastdir"] = "/mnt/onboard/Comic",
    ["lastfile"] = "/mnt/onboard/Comic/Adekan - KCC.epub",
    ["night_mode"] = false,
    ["page_turns_tap_zones"] = "default",
    ["panel_zoom_enabled"] = {
        ["cbt"] = true,
        ["cbz"] = true,
    },
    ["panel_zoom_fallback_to_text_selection"] = {
        ["pdf"] = true,
    },
    ["quickstart_shown_version"] = 202407000204,
    ["reader_footer_custom_text"] = "KOReader",
    ["reader_footer_custom_text_repetitions"] = "1",
    ["reader_footer_mode"] = 4,
    ["screensaver_delay"] = "disable",
    ["screensaver_hide_fallback_msg"] = false,
    ["screensaver_image"] = "/mnt/onboard/.adds/koreader/screenshots/Reader_2024-09-30_194152.png",
    ["screensaver_img_background"] = "black",
    ["screensaver_message_position"] = "middle",
    ["screensaver_msg_background"] = "none",
    ["screensaver_rotate_auto_for_best_fit"] = false,
    ["screensaver_show_message"] = true,
    ["screensaver_stretch_images"] = false,
    ["screensaver_type"] = "image_file",
    ["scroll_method"] = "classic",
    ["show_finished"] = true,
    ["start_with"] = "filemanager",
    ["statistics"] = {
        ["calendar_browse_future_months"] = false,
        ["calendar_nb_book_spans"] = 3,
        ["calendar_show_histogram"] = true,
        ["calendar_start_day_of_week"] = 2,
        ["convert_to_db"] = true,
        ["freeze_finished_books"] = false,
        ["is_enabled"] = true,
        ["max_sec"] = 120,
        ["min_sec"] = 5,
    },
    ["style_tweaks"] = {
        ["footnote-inpage_epub_smaller"] = true,
        ["footnote-inpage_fb2"] = true,
    },
    ["style_tweaks_in_dispatcher"] = {},
    ["terminal_buffer_size"] = 16,
    ["terminal_shell"] = "/bin/sh",
    ["text_lang_fallback"] = "en-US",
    ["toc_items_per_page"] = 14,
    ["vocabulary_builder"] = {
        ["enabled"] = false,
        ["with_context"] = true,
    },
    ["wifi_was_on"] = false,
}
