-- ./settings/profiles.lua
return {
    ["uwu"] = {
        ["b_page_margin"] = 15,
        ["block_rendering_mode"] = 3,
        ["embedded_css"] = true,
        ["embedded_fonts"] = true,
        ["font_base_weight"] = 0,
        ["font_gamma"] = 15,
        ["font_hinting"] = 2,
        ["font_kerning"] = 3,
        ["font_size"] = 22,
        ["h_page_margins"] = {
            [1] = 10,
            [2] = 10,
        },
        ["line_spacing"] = 100,
        ["nightmode_images"] = true,
        ["render_dpi"] = 96,
        ["rotation_mode"] = 0,
        ["set_font"] = "Noto Serif",
        ["settings"] = {
            ["name"] = "uwu",
            ["order"] = {
                [1] = "rotation_mode",
                [2] = "set_font",
                [3] = "font_size",
                [4] = "font_gamma",
                [5] = "font_base_weight",
                [6] = "font_hinting",
                [7] = "font_kerning",
                [8] = "word_spacing",
                [9] = "word_expansion",
                [10] = "visible_pages",
                [11] = "h_page_margins",
                [12] = "sync_t_b_page_margins",
                [13] = "t_page_margin",
                [14] = "b_page_margin",
                [15] = "view_mode",
                [16] = "block_rendering_mode",
                [17] = "render_dpi",
                [18] = "line_spacing",
                [19] = "embedded_css",
                [20] = "embedded_fonts",
                [21] = "smooth_scaling",
                [22] = "nightmode_images",
                [23] = "status_line",
            },
        },
        ["smooth_scaling"] = false,
        ["status_line"] = 1,
        ["sync_t_b_page_margins"] = false,
        ["t_page_margin"] = 15,
        ["view_mode"] = "page",
        ["visible_pages"] = 1,
        ["word_expansion"] = 0,
        ["word_spacing"] = {
            [1] = 95,
            [2] = 75,
        },
    },
}
